# Generated by Django 6.0.1 on 2026-03-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_userprofile_curriculum_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='adviser_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='adviser_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='adviser_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
