# Generated by Django 6.0.1 on 2026-03-27 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_message_adviser_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('units', models.IntegerField(default=3)),
                ('year_level', models.IntegerField()),
                ('semester', models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('Summer', 'Summer')], max_length=10)),
                ('prerequisite_codes', models.CharField(blank=True, help_text='Comma-separated subject codes that must be passed first', max_length=500)),
                ('track', models.CharField(blank=True, help_text='IT elective track (Track 1 / Track 2 / Track 3) or blank for core subjects', max_length=50)),
                ('subject_type', models.CharField(default='core', help_text='core / it_elective / pe / nstp / professional_elective / ge', max_length=20)),
            ],
            options={
                'ordering': ['year_level', 'semester', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('term_label', models.CharField(default='', help_text='e.g. AY 2025-2026 2nd Sem', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_codes', to=settings.AUTH_USER_MODEL)),
                ('approved_subjects', models.ManyToManyField(related_name='enrollment_codes', to='core.curriculumsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_taken', 'Not Yet Taken'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed')], default='not_taken', max_length=20)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('term_taken', models.CharField(blank=True, help_text='e.g. AY 2025-2026 1st Sem', max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_records', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='core.curriculumsubject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TermEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_label', models.CharField(max_length=100)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_enrollments', to='core.enrollmentcode')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_enrollments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_enrollments', to='core.curriculumsubject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'term_label')},
            },
        ),
    ]
