# Generated by Django 6.0.1 on 2026-03-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_curriculumsubject_enrollmentcode_studentcurriculum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
