# Generated by Django 6.0.1 on 2026-04-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message_is_staff_only_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumsubject',
            name='subject_type',
            field=models.CharField(default='core', help_text='core / it_elective / pe / nstp / professional_elective / ge', max_length=50),
        ),
    ]
