# Generated by Django 6.0.1 on 2026-04-09 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_curriculumsubject_subject_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumsubject',
            name='program',
            field=models.CharField(choices=[('BSIT', 'BS Information Technology'), ('BSCS', 'BS Computer Science')], default='BSIT', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='curriculumsubject',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='program',
            field=models.CharField(blank=True, choices=[('BSIT', 'BS Information Technology'), ('BSCS', 'BS Computer Science')], default='BSIT', max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumsubject',
            unique_together={('code', 'program')},
        ),
        migrations.CreateModel(
            name='StaffMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_staff_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_staff_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
