# Generated by Django 6.0.1 on 2026-04-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_curriculumsubject_program_userprofile_last_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='admin_response',
            field=models.TextField(blank=True, help_text='Official response seen by student', null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='adviser_notes',
            field=models.TextField(blank=True, help_text='Internal notes', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('new_student', 'New Student Account'), ('enrollment_code_redeemed', 'Enrollment Code Redeemed'), ('enrollment_approved', 'Enrollment Approved'), ('help_response', 'Help/Report Responded')], max_length=50),
        ),
    ]
