# Generated by Django 6.0.1 on 2026-04-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_formsubmission_admin_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meeting_link',
            field=models.URLField(blank=True, help_text="Adviser's default meeting room link", max_length=500, null=True),
        ),
    ]
