# Generated by Django 6.0.1 on 2026-04-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_is_email_verified_userprofile_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='actual_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='actual_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('new_student', 'New Student Account'), ('enrollment_code_redeemed', 'Enrollment Code Redeemed'), ('enrollment_approved', 'Enrollment Approved'), ('help_response', 'Help/Report Responded'), ('incoming_call', 'Incoming Video Call')], max_length=50),
        ),
    ]
