# Generated by Django 6.0.1 on 2026-04-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_appointment_actual_end_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Status'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Done'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Default platform meeting room link', max_length=500, null=True),
        ),
    ]
